source ~/dotfiles/vim/scripts/getos.vim
source ~/dotfiles/vim/scripts/sourcing.vim

let s:os = GetOS()
let s:host = split(hostname(), '\.')[0]

" colors
" colorscheme candy
colors molokai

" font
if s:os[0] == 'linux'
  set guifont=DejaVu\ Sans\ Mono\ 10
elseif s:os[0] == 'macos'
  set guifont=Andale_Mono:h14
endif

" window size
set columns=125

if s:host=='aki'
  set lines=50
else
  set lines=40
endif

" syntax highlight always on
syntax on

"antialias font
set antialias

" line numbers
set number

" no toolbar
set guioptions-=T

" horizontal scoll bar
set guioptions+=b

" copy to clipboard
set cb=unnamed

" subtle color of current line/col
hi CursorLine guibg=#202020
hi CursorColumn guibg=#101010
" TODO: figure out how to make this not nuke other backgrounds
set cursorline
" set cursorcolumn

hi User1 guibg=#00FF00 guifg=#000000
hi User2 guibg=#FF0000 guifg=#000000

" hi Comment guifg=#ff99cc " candy
hi SpecialKey guifg=#303233 " tab markers, molokai

call SourceCustomFiles("~/dotfiles/vim/gvimrc")
