# If not running interactively, don't do anything
[ -z "$PS1" ] && return

. ~/dotfiles/bash/prexec.bash
. ~/dotfiles/bash/colors.bash
. ~/dotfiles/bash/os.bash

if [ -f ~/dotfiles/bash/prompt.$hostname.bash ]
then . ~/dotfiles/bash/prompt.$hostname.bash
else . ~/dotfiles/bash/prompt.bash
fi

[ $hostname = aki ] && . ~/dotfiles/bash/ssh-agent.bash

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if which dircolors > /dev/null 2>&1 && [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
fi

# some more ls aliases
alias ll='ls -l'

alias dc=cd

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
[ -f /etc/bash_completion ] && . /etc/bash_completion
[ -f /etc/profile.d/bash-completion.sh ] && . /etc/profile.d/bash-completion.sh

#export CSCOPE_DB=

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export HISTSIZE=50000
#export HISTTIMEFORMAT="%m-%d %H:%M"

if [ $BASH_VERSINFO -gt 3 ]; then
	shopt -s autocd    # executing a dir cds into it
	shopt -s globstar  # enable **
	shopt -s dirspell  # fix dir spelling in tab completion
fi

#export PROMPT_DIRTRIM=5


# recursive grep by extension
# ex: f c -i 'hello world'
f () {
  ext=$1
  shift
  find . -path "*.$ext" -type f -exec grep -Hn "$@" {} \;
}

# find file by name
# fn [path] file
# ex: fn src *.java
fn () {
  path=./
  if [ $# -gt 1 ]; then
    path="$1"
    shift
  fi

  find "$path" -iname "$@"
}

# grails crap
export PATH=$PATH:~/grails/bin
export GWT_HOME=~/Downloads/gwt-linux-1.7.1

# ccache
[ -d /usr/lib/ccache/bin ] && export PATH=/usr/lib/ccache/bin:$PATH

export FIGNORE=.svn:.git

